#!/bin/sh
# -*- python -*-
# Shell commands follow
# Next line is bilingual: it starts a comment in Python, and is a no-op in shell
""":"
# Find a suitable Python interpreter
for cmd in python3 python python2 ; do
   command -v > /dev/null $cmd && exec $cmd $0 "$@"
done

echo "The quadplay local script requires Python (2.x or 3.x) to be installed on your system." >2

exit 2

":"""
# Previous line is bilingual: it ends a comment in Python, and is a no-op in shell
# Shell commands end here
# Python script follows

import os, time, platform, sys, threading, socket, argparse, multiprocessing, json, ssl, codecs

__doc__ = "Quadplay Fantasy Console launcher script."

version = str(sys.version_info.major) + '.' + str(sys.version_info.minor)

# Largest common prefix of quad_path and game_path. Root for web serving
web_path = None

# Subdirectories of web_path that are permitted for http access
whitelist = None

onWindows = (platform.system() == 'Windows')
onMac = (platform.system() == 'Darwin')

try:
    # Python 3.7
    from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
    QuadplayHTTPServer = ThreadingHTTPServer
    print('Initializing Quadplay server using Python ' + version + ' ThreadingHTTPServer')
    
except ImportError:
    try:
        # Python 3
        from http.server import HTTPServer, SimpleHTTPRequestHandler
        print('Initializing Quadplay server using Python ' + version + ' HTTPServer')
        QuadplayHTTPServer = HTTPServer
    except ImportError:
        # Python 2
        from SimpleHTTPServer import SimpleHTTPRequestHandler
        import SocketServer
        QuadplayHTTPServer = SocketServer.TCPServer
        print('Initializing Quadplay server using Python ' + version + ' SocketServer.TCPServer')
        
# Handles serving from multiple directories
#
# See https://github.com/python/cpython/blob/master/Lib/http/server.py for
# the base class implementation and internal methods
class QuadplayHTTPRequestHandler(SimpleHTTPRequestHandler):
    def list_directory(self, path):
        # Prevent directory listing
        self.send_error(404, 'No permission to list directory')
        return None
        
    # Used for the IDE to write files. Currently disabled on the IDE side
    def do_POST(self):
        if args.host:
           print('Refused POST command while running with --host')
           return
        
        if self.client_address[0] != '127.0.0.1':
           print('Refused POST command from non-local address', self.client_address[0])
           return
        
        print('\n\nReceived POST from ', self.client_address[0], '\n\n')

        content_len = int(self.headers['Content-Length'])
        #int(self.headers.getheader('content-length', 0))
        post_body = self.rfile.read(content_len)

        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()
        
        #print("\nPOST contents:\n")
        #print(post_body)
        object = json.loads(post_body)
        command = object['command']
        if command == 'write_file':
           filename = object['filename'][1:]
           encoding = object['encoding']
           contents = object['contents']
           print('wrote ', encoding, 'file: ', filename)
           if encoding == 'binary':
              with open(filename, 'wb') as f: f.write(contents)
           else:
              with codecs.open(filename, 'w', encoding) as f: f.write(contents)
              
        self.wfile.write('OK'.encode('utf8'))

              
    def do_GET(self):
        global whitelist, web_path
        
        # Remove the query and collapse any ..
        path = os.path.normpath(self.path.split('?')[0]).replace('\\', '/')

        # Security: Check if path has a prefix in whitelist
        if not any([path.startswith(prefix) for prefix in whitelist]):
            self.send_error(404, 'Illegal path: ' + path)
        
        f = self.send_head()
        if f:
            try:
                self.copyfile(f, self.wfile)
            finally:
                f.close()
        """
            def do_GET(self):
        return super(QuadplayHTTPRequestHandler, self).do_GET()"""
     
    def translate_path(self, path):
        # Intentionally use Python 2 super syntax
        result = SimpleHTTPRequestHandler.translate_path(self, path)
        return result
     

def parse_args():
    """ parse arguments out of sys.argv """
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        "--host",
        action="store_true",
        default=False,
        help="hosting mode - allow other machines to connect to this one to play on mobile devices"
    )
    parser.add_argument(
        'gamepath',
        type=str,
        default="",
        nargs='?',
        help=(
            'Game to load.  If not specified, loads default loader scene.'
            ' Example: examples/accel_demo'
        )
    )
    parser.add_argument(
        "-p",
        "--port",
        type=int,
        default=8000,
        help="Port to run the server on."
    )

    return parser.parse_args()

# Args must be initialized to a constant before launchServer is defined
# because of the way that multiprocess serialization works on ThreadingHTTPServer
args = parse_args()
if onWindows and args.gamepath:
    # Make drive letters canonical
    if args.gamepath[1] == ':':
        args.gamepath = args.gamepath[0].upper() + args.gamepath[1:]

        
# Makes a path absolute for the web server root
def platform_www_abspath(p):
    if onWindows:
        p = p[len(web_path):]
        if not p.endswith('.game.json'): p = os.path.join(p, '')
        t = p.replace('\\', '/')
        if len(t) > 1 and t[1] != ':' and t[0] != '/': t = '/' + t
        return t
    else:
        p = p[len(web_path)+1:]
        if p == '':
            return ''
        elif p.endswith('.game.json'):
            return os.path.join('/', p)            
        else:
            return os.path.join('/', p, '')

    
# Process paths at top level so that they can be inherited by ThreadingHTTPServer
if True:
    quad_path = os.path.abspath(os.path.dirname(__file__))

    # Compute the serving paths
    if args.gamepath and not args.gamepath.startswith('http:'):
       game_path = os.path.abspath(args.gamepath)

       if game_path.endswith('.game.json'):
          game_path = os.path.dirname(game_path)
       
       whitelist = [quad_path, game_path]
       
       # Common ancestor
       web_path = os.path.dirname(os.path.commonprefix([os.path.join(p, '') for p in whitelist]))
    else:
       web_path = quad_path
       whitelist = [quad_path]

    # Strip the common prefix
    whitelist = [platform_www_abspath(p).replace('\\', '/') for p in whitelist]
    quad_path = whitelist[0]
    web_path = web_path.replace('\\', '/')

    #print("web_path = '" + web_path + "'")
    #print("quad_path = '" + quad_path + "'")
    #print('whitelist = ', whitelist)

    
# SSL support doesn't work yet due to self-signed certificates
useSSL = False

# Runs in a different process
def launchServer():
    global httpd, args, web_path
    
    # Serve from the common directory
    old_path = os.getcwd()
    os.chdir(web_path)
    
    try:
        # '' = 0.0.0.0 = all local IP addresses, needed for
        # supporting devices other than just localhost
        server_address = ('' if args.host else 'localhost', args.port)
        httpd = QuadplayHTTPServer(server_address, QuadplayHTTPRequestHandler)

        if useSSL:
            httpd.socket = ssl.wrap_socket(httpd.socket, 
                                           keyfile='console/ssl/local-key.pem', 
                                           certfile='console/ssl/local-cert.pem',
                                           do_handshake_on_connect=False,
                                           server_side=True)
        httpd.serve_forever()
    except OSError as e:
        print(e)
        print('Not starting a local server, since one is already running.');
        
    os.chdir(old_path)

        
def main():
    global whitelist, web_path

    try:
       import msvcrt
    except ImportError:
       import termios, atexit, select
       stdinFd = sys.stdin.fileno()
       new_term = termios.tcgetattr(stdinFd)
       old_term = termios.tcgetattr(stdinFd)
       def set_normal_term():
           termios.tcsetattr(stdinFd, termios.TCSAFLUSH, old_term)

       # New terminal setting unbuffered
       new_term[3] = (new_term[3] & ~termios.ICANON & ~termios.ECHO)
       termios.tcsetattr(stdinFd, termios.TCSAFLUSH, new_term)

       # Support normal-terminal reset at exit
       atexit.register(set_normal_term)

    myip = '127.0.0.1'
    if args.host:
        try:
            print('Getting IP address...')
            myip = ''

            # just try this first on mac because the other approaches fail so frequently
            if onMac:
               myip = (os.popen('ipconfig getifaddr en0').read().strip() or
                       os.popen('ipconfig getifaddr en1').read().strip())
            if not myip: myip = socket.gethostbyname(socket.gethostname())
        except:
            if onMac:
                # The above can fail apparently randomly on MacOS (https://bugs.python.org/issue35164)
                # and that has happened to us. This is a workaround:
                print('gethostbyname failed due to a known MacOS internal error. Falling back to\nipconfig...')
                
                myip = os.popen('ipconfig getifaddr en0').read().strip()
                if not myip:
                   print('Could not find en0. Looking for en1...')
                   myip = os.popen('ipconfig getifaddr en1').read().strip()
                
                if not myip:
                    print('WARNING: ipconfig could not find a valid en0 or en1 adapter. Server IP address is unknown.')
                    myip = '127.0.0.1'
                else:
                    print('WARNING: gethostbyname unexpectedly failed. Server IP address is unknown.')
                    myip = '127.0.0.1'

    url = 'http' + ('s' if useSSL else '')+ '://' + myip + ':' + str(args.port)
    if not quad_path or quad_path[0] != '/': url += '/'
    url += os.path.join(quad_path, 'console/quadplay.html') + '?IDE=1&fastReload=1'
    print('_________________________________________________________________________\n')

    if args.gamepath != '':
        t = args.gamepath
        if not t.startswith('http://'):
            t = platform_www_abspath(os.path.abspath(t))
            if t and not onWindows and t[0] != '/': t = '/' + t
        url += '&game=' + t
    else:
        print('Loading default launcher game. You can supply the URL or local relative path to your game on\nthe command line, for example "quadplay foo/mygame", to load it directly.\n')

    print('\nServing from:\n\n   ' + url)
                 
    if args.host:
        # Do not support POST in host mode
        print('\n\nNote that your firewall may need to be configured to load on other devices.\n')
    else:
        url += '&quadserver=1'
    
    # Run from the quadplay path
    print('\n   the quad:// root path is ' + os.path.abspath(os.path.dirname(__file__)).replace('\\', '/') + '/\n')
    

    # Platform independent keyboard key press detection
    def kbhit():
       if onWindows:
          return msvcrt.kbhit()
       else:
          dr, dw, de = select.select([sys.stdin], [], [], 0)
          return dr != []

    httpd = 0

    serverThread = multiprocessing.Process(target=launchServer)
    print('Starting local server thread...')
    serverThread.start()
    print('\n**Press any key to terminate the server when done**\n')
    time.sleep(2)

    if onWindows:
        # Require NO surrounding quotes on Windows for it to interpret the URL.
        # Must escape & as ^&.
        os.system('start ' + url.replace('&', '^&'))
    elif onMac:
        # Require quotes on Unix systems so that bash does not interpret &
        # as a shell option to run in another thread
        os.system('open "' + url + '"')
    else:
        os.system('xdg-open "' + url + '"')

    while not kbhit():
        time.sleep(0.25)

    print('\nShutting down...')

    # Attempt to gracefully shut down
    if httpd: threading.Thread(target=lambda : httpd.shutdown())
    time.sleep(1)
    serverThread.terminate()

    return 0

if __name__ == "__main__":
    sys.exit(main())
